[package]
name = "l4re-libc"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[lib]
name = "l4re_libc"
crate-type = ["rlib", "staticlib"]

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
