[package]
name = "driver_client"
version = "0.1.0"
edition = "2021"

[dependencies]
l4re = { path = "../../../crates/l4re" }
l4re-libc = { path = "../../../crates/l4re-libc" }
l4 = { path = "../../../crates/l4" }

[workspace]
