[package]
name = "driver_server"
version = "0.1.0"
edition = "2021"

[dependencies]
l4 = { path = "../../crates/l4" }
l4re = { path = "../../crates/l4re" }
l4re-libc = { path = "../../crates/l4re-libc" }
driver = { path = "../driver" }
virtio_frontend = { path = "../virtio_frontend" }

[workspace]
